services:
  - type: web
    name: atlasmarkets-anubis
    dockerfilePath: crypto_api/Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: FACILITATOR_URL
        value: https://facilitator.payai.network
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: web
    name: atlasmarkets-viking
    dockerfilePath: stock_api/Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: FACILITATOR_URL
        value: https://facilitator.payai.network
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: web
    name: atlasmarkets-apollo
    dockerfilePath: forex_api/Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: FACILITATOR_URL
        value: https://facilitator.payai.network
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: web
    name: atlasmarkets-pollux
    dockerfilePath: commodities_api/Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: FACILITATOR_URL
        value: https://facilitator.payai.network
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: web
    name: atlasmarkets-dagon
    dockerfilePath: onchain_api/Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: FACILITATOR_URL
        value: https://facilitator.payai.network
      - key: PYTHONUNBUFFERED
        value: "1"